export const prompts = [
'¿Cuál fue la verdadera razón por la que te echaron del trabajo?',
'¿Qué frase jamás debería aparecer en una invitación de boda?',
'¿Qué encontró tu cita cuando revisó tu historial de búsqueda?',
'¿Cómo arruinaste la cena familiar antes de que llegara el postre?',
'¿Qué secreto confesaste después de dos copas de más?',
'¿Qué decía la nota que dejaron en la puerta de tu casa?',
'¿Por qué te expulsaron del grupo de WhatsApp?',
'¿Cuál fue tu peor intento de impresionar a alguien?',
'¿Qué jamás debería decir un psicólogo al terminar la sesión?',
'¿Por qué tu vecino ahora evita cruzarte en el ascensor?',
'¿Qué promesa hiciste en una primera cita y ahora tenés que cumplir?',
'¿Qué actividad prohibieron definitivamente en el retiro de la empresa?',
'¿Qué decía el último audio que mandaste al chat equivocado?',
'¿Qué había dentro de la misteriosa caja debajo de la cama?',
'¿Cuál fue el motivo real de tu separación?',
'¿Qué dice la letra chica de tu contrato de pareja?',
'¿Qué consejo dio el peor padrino de bodas del mundo?',
'¿Qué decía el cartel que pusieron frente a tu casa?',
'¿Qué mentira absurda sostenés desde hace años?',
'¿Qué hiciste cuando te dejaron solo a cargo del negocio?',
'¿Qué confesión hizo que cancelaran el cumpleaños?',
'¿Cuál fue el peor nombre posible para una nueva app de citas?',
'¿Qué evento terrible figura en tu calendario como “plan tranqui”?',
'¿Qué jamás deberías decir en una entrevista de trabajo?',
'¿Por qué no te invitan más a jugar juegos de mesa?',
'¿Qué dijo tu familia cuando conoció a tu nueva pareja?',
'¿Cuál sería la peor cláusula de un contrato de amistad?',
'¿Qué castigo inventó el consorcio para vos?',
'¿Cuál fue la última gota para que te bloquearan?',
'¿Qué ocurrió durante los cinco minutos sin cámaras?',
'¿Qué frase convirtió una disculpa en algo muchísimo peor?',
'¿Qué plan presentaste para salvar la fiesta y salió mal?',
'¿Qué vas a contar en el brindis que nadie quiere escuchar?',
'¿Cuál fue tu gran idea para dividir la cuenta?',
'¿Qué descubriste cuando alguien compartió pantalla por accidente?',
'¿Cuál es tu estrategia para salir de una cita espantosa?',
'¿Qué detalle omitiste al contar la historia la primera vez?',
'¿Qué harías si fueras administrador del chat familiar por una noche?',
'¿Cuál fue la excusa más sospechosa para llegar tarde?',
'¿Qué regalo hizo que dejaran de hablarse dos familias?',
'¿Cómo conseguís que te dejen de pedir favores?',
'¿Qué mensaje apareció en el celular durante el brindis?',
'¿Qué mentira contaste para entrar a una fiesta privada?',
'¿Cómo convertiste una ruptura en un negocio?',
'¿Qué diría la lápida de tu reputación social?',
'¿Qué escena incómoda interrumpió la luna de miel?',
'¿Por qué tu ex y tu actual pareja ahora son mejores amigos?',
'¿Qué mensaje jamás deberías mandar después de las tres de la mañana?',
'¿Qué confesión arruinó el funeral de tu mascota?',
'¿Cuál es la cláusula secreta de tu acuerdo con tu ex?',
'¿Qué encontraron enterrado en el patio durante tu cumpleaños?',
'¿Por qué tu familia te pidió que dejaras de hablar con el espejo?',
'¿Qué decía el último mensaje enviado desde el celular del difunto?',
'¿Qué actividad hizo que clausuraran el geriátrico?',
'¿Por qué hay una habitación de tu casa que nadie puede abrir?',
'¿Qué descubriste al revisar las cámaras del sótano?',
'¿Cuál era el ingrediente secreto del guiso de la abuela?',
'¿Qué llevó el tío raro al bautismo?',
'¿Por qué el sacerdote abandonó la ceremonia?',
'¿Qué apareció escrito en la pared después del apagón?',
'¿Cuál fue la verdadera causa de la intoxicación en la fiesta?',
'¿Qué encontraron dentro de la piñata?',
'¿Por qué tu mascota figura como única heredera?',
'¿Qué vendía realmente el puesto del fondo de la feria?',
'¿Qué secreto familiar reveló el test de ADN?',
'¿Por qué el payaso salió corriendo de tu cumpleaños?',
'¿Qué objeto jamás debería vibrar dentro de un ataúd?',
'¿Qué había en el freezer que obligó a cancelar la cena?',
'¿Qué confesó la abuela después de fingir demencia durante veinte años?',
'¿Por qué la policía ya conocía tu nombre?',
'¿Qué práctica prohibieron después de tu primera clase de yoga?',
'¿Cuál era el verdadero propósito del grupo de padres?',
'¿Qué encontraron los bomberos debajo de tu cama?',
'¿Qué frase arruinó definitivamente el velorio?',
'¿Por qué tu vecino recibe paquetes con tu nombre?',
'¿Qué ritual realizás antes de una primera cita?',
'¿Qué detalle inquietante tenía el muñeco de tu infancia?',
'¿Qué ofrecía el menú secreto del restaurante?',
'¿Por qué el psicólogo empezó a grabar tus sesiones?',
'¿Qué se llevó tu ex además de tu dignidad?',
'¿Qué había realmente dentro del tupper que nadie quería devolver?',
'¿Por qué todos en el pueblo tienen la misma foto tuya?',
'¿Qué escucharon salir del placard durante la cena?',
'¿Cuál fue el peor momento para descubrir que el micrófono seguía encendido?',
'¿Qué decía la cláusula número 13 del contrato matrimonial?',
'¿Por qué tuvieron que cambiarle el nombre al orfanato?',
'¿Qué souvenir entregaron en el funeral?',
'¿Qué reveló tu historial de compras a las tres de la mañana?',
'¿Cuál fue tu contribución al mercado negro?',
'¿Qué promesa hiciste para salir del sótano?',
'¿Por qué el cadáver tenía tu tarjeta de presentación?',
'¿Qué encontraron en la valija que compraste usada?',
'¿Cuál fue el verdadero motivo de la desaparición del animador?',
'¿Qué hacías desnudo en el techo del consorcio?',
'¿Qué frase jamás debería decir quien está cavando una fosa?',
'¿Por qué tu fiesta de quince terminó en un operativo policial?',
'¿Qué negocio secreto funciona detrás de la veterinaria?',
'¿Qué descubriste al abrir el cajón prohibido de tus padres?',
'¿Por qué el bebé pronunció tu nombre antes de aprender a hablar?',
'¿Qué contenía el audio titulado “borrar después de escuchar”?',
'¿Cuál era la contraseña del grupo secreto de la familia?',
'¿Qué pasó durante esos siete minutos que faltan en la grabación?',
'¿Por qué hay una estatua tuya en el fondo del río?',
'¿Qué utilizaste para decorar el altar improvisado?',
'¿Qué regalo de bodas obligó a evacuar el salón?',
'¿Qué encontró tu cita flotando en la bañera?',
'¿Por qué el médium se negó a contactar a tu abuelo?',
'¿Qué vendiste para pagar la despedida de soltero?',
'¿Qué decía la nota escondida dentro de la urna funeraria?',
'¿Cuál era el verdadero trabajo de tu abuelo?',
'¿Qué hizo que el exorcista pidiera refuerzos?',
'¿Por qué te prohibieron volver al cementerio?',
'¿Qué hacía tu foto en el altar de una secta?',
'¿Qué secreto protege el grupo de WhatsApp del consorcio?',
'¿Cuál fue el peor uso posible para una impresora 3D?',
'¿Qué encontraron en el doble fondo de la cuna?',
'¿Por qué la niñera cambió de identidad después de trabajar para vos?',
'¿Qué recuerdo de tus vacaciones confiscó la aduana?',
'¿Qué respondió la inteligencia artificial cuando le preguntaste cómo ocultarlo?',
'¿Cuál era la consigna de la fiesta que nadie se animó a cumplir?',
'¿Por qué el novio llegó esposado a la ceremonia?',
'¿Qué objeto apareció misteriosamente en todas las fotos familiares?',
'¿Qué mensaje dejó el anterior dueño de la casa debajo del empapelado?',
'¿Qué detalle hizo sospechar que tu amigo invisible no era imaginario?',
'¿Por qué tu nombre aparece escrito en todos los baños públicos?',
'¿Qué había detrás de la puerta marcada “personal autorizado”?',
'¿Qué subastaron para financiar el viaje de egresados?',
'¿Cuál fue la última voluntad más difícil de explicar ante un juez?',
'¿Qué encontraron dentro de la torta antes de cortarla?',
'¿Por qué el chofer del remise pidió protección de testigos?',
'¿Qué servicio clandestino ofrecías desde el lavadero?',
'¿Qué escuchó Alexa que ahora forma parte de una investigación?',
'¿Por qué tu clon exige una indemnización?',
'¿Qué provocó el silencio incómodo durante la autopsia?',
'¿Cuál era el plan B si alguien sobrevivía?',
'¿Qué había escrito en la parte de atrás del cuadro familiar?',
'¿Por qué el detective decidió abandonar tu caso?',
'¿Qué descubriste al seguir el extraño olor del pasillo?',
'¿Qué objeto familiar lleva generaciones sin ser lavado?',
'¿Por qué tu cumpleaños figura como feriado en una comunidad aislada?',
'¿Qué hacían doce desconocidos vestidos como vos frente a tu casa?',
'¿Cuál fue la peor frase posible para despertarse después de una cirugía?',
'¿Qué contenía el paquete que llegó sin remitente?',
'¿Por qué tu dentista conserva una llave de tu departamento?',
'¿Qué tradición familiar debería haber sido denunciada hace décadas?',
'¿Qué apareció en la ecografía que nadie supo explicar?',
'¿Por qué tu ex contrató a un sacerdote, un abogado y un cerrajero?',
'¿Qué descubriste demasiado tarde sobre el Airbnb?',
'¿Qué prueba destruiste justo antes de empezar esta partida?',
'¿Qué van a encontrar cuando finalmente revisen tu baúl?',
'¿Qué frase convirtió una noche romántica en una investigación policial?',
'¿Qué objeto totalmente inesperado encontraron debajo de tu cama?',
'¿Por qué tu ex todavía conserva las llaves de tu dormitorio?',
'¿Qué pedido extraño hizo tu cita antes de sacarse la ropa?',
'¿Qué mensaje picante mandaste por error al grupo familiar?',
'¿Cuál es el lugar más inapropiado donde intentaste seducir a alguien?',
'¿Qué palabra de seguridad arruinó completamente el momento?',
'¿Qué secreto reveló tu historial de compras para adultos?',
'¿Por qué tuvieron que cambiar las sábanas tres veces?',
'¿Qué fantasía confesaste después de demasiadas copas?',
'¿Qué ruido imposible de explicar escucharon los vecinos?',
'¿Cuál fue el peor comentario que recibiste después de desnudarte?',
'¿Qué objeto cotidiano usaste de una forma que el fabricante jamás imaginó?',
'¿Por qué tu cita llamó a un técnico en pleno encuentro?',
'¿Qué descubriste cuando encendieron la luz?',
'¿Qué cláusula picante incluiste en el contrato de pareja?',
'¿Qué dijo tu suegra al encontrar el juguete misterioso?',
'¿Por qué tu amante llegó acompañado por un escribano?',
'¿Cuál fue la excusa más absurda para explicar esas esposas?',
'¿Qué arruinó el encuentro romántico en el asiento trasero?',
'¿Qué prometía el anuncio de citas que resultó ser completamente falso?',
'¿Qué detalle íntimo apareció proyectado durante una reunión de trabajo?',
'¿Cuál es tu técnica de seducción más cuestionable?',
'¿Qué regalo erótico terminó en manos de la persona equivocada?',
'¿Qué pasó en el baño que nadie se anima a contar?',
'¿Qué confesión hizo que tu cita volviera a vestirse inmediatamente?',
'¿Por qué hay una cámara, tres velas y un casco junto a tu cama?',
'¿Qué descubriste dentro del cajón secreto de tu pareja?',
'¿Cuál fue el peor nombre posible para tu video privado?',
'¿Qué ocurrió realmente durante la supuesta “noche de juegos”?'
];
export const answers = [
'El grupo secreto donde opinábamos de todos tenía de administrador al jefe.',
'Un PowerPoint de 74 diapositivas explicando por qué yo tenía razón.',
'Le puse precio de entrada a una reunión obligatoria.',
'Una captura de pantalla enviada exactamente a la persona de la captura.',
'Inventé un primo abogado y ahora todos le piden asesoramiento.',
'Un “te extraño” copiado y pegado en tres chats al mismo tiempo.',
'Dije “confíen en mí” mientras borraba las cámaras.',
'El Excel con mis amigos ordenados por utilidad.',
'Le pedí referencias a la ex de mi cita.',
'Una cuenta falsa que por error empezó a salir con mi cuenta real.',
'Se enteraron de que mi mascota tiene un perfil para espiarlos.',
'Organizamos una intervención, pero el invitado era otra persona.',
'Una presentación titulada “No es una estafa si somos amigos”.',
'La lista de invitados estaba ordenada por patrimonio.',
'Grabé un audio de disculpas y lo mandé como tono de llamada.',
'Una membresía premium para acceder a mis sentimientos.',
'Confundí una despedida de soltero con una reunión de padres.',
'Puse a votación quién de la mesa debía pagar por todos.',
'Fingí saber leer el tarot para terminar una discusión.',
'La planilla donde registraba cada favor que me debían.',
'Dije que era una sorpresa para ganar tiempo. No había sorpresa.',
'Un emprendimiento de consejos amorosos manejado por mis ex.',
'Le pedí a la IA que escribiera mi personalidad para la cita.',
'Imprimí nuestros chats y pedí una segunda opinión al grupo.',
'Una invitación con dress code: gente que no me caiga mal.',
'Le dije “sos como familia” para no devolverle la plata.',
'Un certificado de buena persona firmado por mí.',
'La carpeta “pruebas por si algún día me discuten”.',
'Un brindis que empezó con “ya que estamos todos acá...”.',
'Le cobré a mi hermano por usar una anécdota mía.',
'Una playlist llamada “canciones para cuando se den cuenta”.',
'Fui a la cena solo para ver quién hablaba mal de mí.',
'Una encuesta anónima que solo podía responder yo.',
'Un mensaje programado para pelear después de mis vacaciones.',
'Me presenté como inversor porque una vez compré criptomonedas.',
'La única copia del contrato estaba escrita en una servilleta.',
'Pedí que me aplaudieran por hacer el mínimo indispensable.',
'Una lista de excusas con fecha de vencimiento.',
'La grabación completa de una charla que “nunca ocurrió”.',
'Un recibo por daños emocionales con impuestos incluidos.',
'Mi discurso incluyó un ranking de parejas anteriores.',
'Organicé un amigo invisible y me asigné todos los regalos.',
'La tarjeta decía “perdón por lo que todavía no sabés”.',
'La contraseña del Wi-Fi era una confesión demasiado específica.',
'Lo llamé networking, pero era una cita con cuatro personas.',
'Un contrato de confidencialidad para contar un chisme menor.',
'Puse mi cumpleaños el mismo día para robarme el festejo.',
'La nota decía “devolvé el tupper y nadie sale lastimado”.',
'Una devolución por escrito de la personalidad de cada invitado.',
'Le di “me gusta” a una foto de hace siete años.',
'Una coartada con tantos detalles que parecía ensayada.',
'Una cita doble sin avisarle a ninguna de las otras tres personas.',
'Convertí el velorio de una planta en un evento con entradas.',
'Le pedí a mi madre que confirmara una mentira frente a todos.',
'La última foto era yo festejando antes de que terminara la relación.',
'Una encuesta para decidir si seguíamos siendo amigos.',
'Llegué con un escribano para repartir la pizza.',
'La historia que subí tenía de fondo mi otra cita.',
'Un sticker mío llorando que uso para pedir plata.',
'Una carpeta compartida titulada “personas que me deben disculpas”.',
'Le puse cinco estrellas al negocio porque me debían un favor.',
'Un tutorial sobre cómo salir de un grupo sin que se note.',
'Fui vestido de testigo protegido a una reunión de consorcio.',
'Un cupón de descuento para mi próximo pedido de perdón.',
'La foto familiar incluía a alguien que nadie conocía.',
'Un audio de nueve minutos que terminaba en “era joda”.',
'La factura detallaba abrazos, favores y escucha activa.',
'Me anoté como testigo en una discusión que yo había provocado.',
'Una alarma llamada “actuá normal” sonó en el peor momento.',
'El tatuaje decía el nombre de alguien que todavía no conocía.',
'Una caja fuerte que guardaba únicamente capturas de pantalla.',
'La excusa era “me robaron la identidad”, pero llevaba mi ropa.',
'Una disculpa redactada como si fuera una oferta laboral.',
'Me declaré inocente antes de que alguien me acusara.',
'La invitación incluía un formulario para elegir bando.',
'Un grupo de apoyo para personas que me conocen.',
'El regalo era una foto mía firmada con dedicatoria.',
'Pagué la terapia de alguien para que me diera la razón.',
'Una reserva para dos en el restaurante donde trabajaba mi ex.',
'Mi plan de ahorro consistía en hacerme el olvidadizo.',
'Usé la excusa “es contenido” para justificarlo todo.',
'Me llevé una carpeta con pruebas a un asado.',
'Un sistema de puntos para evaluar las visitas familiares.',
'El código QR llevaba a una encuesta sobre mi desempeño.',
'La presentación arrancaba con “antes de juzgarme, escuchen”.',
'Una nota de voz marcada como “escuchar con abogado”.',
'El brindis reveló que había dos aniversarios esa noche.',
'Un perfil de citas administrado por mi suegra.',
'Hice una colecta para financiar mi propia disculpa.',
'Una lista de reproducción llamada “indirectas, volumen máximo”.',
'Las cámaras no fallaron: yo las tapé con un cartel de “privacidad”.',
'Una reunión urgente para decidir quién había exagerado más.',
'La transferencia decía “pago por silencio” en el concepto.',
'Todos recibieron la misma carta, pero con distinto nombre.',
'Le pedí a un desconocido que fingiera ser mi ex jefe.',
'Un calendario compartido con horarios para ignorarnos.',
'La verdad salió a la luz por un emoji mal elegido.',
'Me hice pasar por organizador para sentarme en la mesa principal.',
'Un brindis de despedida que nadie sabía que era de despedida.',
'Un perfil de citas con fotos del funeral de mi dignidad.',
'Mi ex descubrió que seguía usando nuestra cuenta compartida para buscar pareja.',
'Mandé un “te amo” al chat equivocado y decidí sostenerlo.',
'La fiesta sorpresa era para anunciar que me había fugado con el catering.',
'Tenía tres coartadas, dos parejas y una sola reserva.',
'Le pedí el número a alguien durante la discusión de mi ruptura.',
'Una despedida de soltero patrocinada por mi terapeuta.',
'La captura del chat privado apareció en la pantalla del velorio.',
'Le dije que buscaba una relación seria. Era una investigación de mercado.',
'El ramo de flores venía con una factura a nombre de mi ex.',
'Mi disculpa terminaba con “si querés la versión completa, suscribite”.',
'En el brindis agradecí a mi pareja y a la otra persona por separado.',
'La excusa involucraba un retiro espiritual que tenía barra libre.',
'El test de compatibilidad lo había escrito yo para aprobarlo.',
'Una hoja de cálculo con mis citas y su potencial de herencia.',
'La última frase fue “no revisen el grupo secundario”.',
'Unas esposas, dos antifaces y una explicación que nadie creyó.',
'El juguete para adultos seguía conectado al Bluetooth del living.',
'Una foto íntima impresa por error en la librería del barrio.',
'La palabra de seguridad era “AFIP”.',
'Tres litros de lubricante y ningún recuerdo de haberlos comprado.',
'Una lista de posiciones ordenadas por riesgo de lesión laboral.',
'El disfraz de enfermero venía con matrícula profesional falsificada.',
'Una noche de pasión supervisada por el grupo familiar.',
'El vibrador apareció vinculado al parlante de la abuela.',
'Una cita romántica que requería casco, rodilleras y consentimiento por escrito.',
'La cámara estaba apagada, pero el vivo de Instagram no.',
'Un paquete discreto entregado durante el almuerzo familiar.',
'La fantasía incluía un escribano, dos testigos y cobertura médica.',
'Un audio sensual con la alarma de monotributo sonando de fondo.',
'La habitación temática tenía más cámaras que una casa de Gran Hermano.',
'Un masaje con final tan feliz que terminó en auditoría contable.',
'La foto prohibida terminó como imagen del grupo del consorcio.',
'Un contrato de exclusividad redactado sobre una caja de preservativos.',
'La lencería tenía un bolsillo secreto para guardar evidencia.',
'Una videollamada erótica con veintisiete participantes accidentales.',
'El sacerdote reconoció las esposas y prefirió no explicar por qué.',
'Un calendario compartido para coordinar amantes y fumigaciones.',
'La cama giratoria seguía registrada como maquinaria industrial.',
'Una encuesta de satisfacción enviada cinco minutos después.',
'El gemido era real; la identidad de quien lo emitió sigue en discusión.',
'Un striptease interrumpido por una actualización obligatoria de Windows.',
'La cita pidió factura A antes de quitarse el pantalón.',
'Un tatuaje íntimo con un error de ortografía imperdonable.',
'El aceite para masajes tenía gusto a pollo al horno.',
'Una noche de juegos que requería firmar un deslinde de responsabilidad.',
'Veintitrés muñecas mirándome dormir desde una repisa.',
'Una conversación diaria con la mancha de humedad del baño.',
'El maniquí del living estaba vestido como mi ex.',
'Una colección de uñas etiquetadas por fecha y estado de ánimo.',
'El altar dedicado a una paloma que una vez me sostuvo la mirada.',
'Siete despertadores programados para recordar que debo actuar normal.',
'Una heladera llena de frascos que decían “todavía sirve”.',
'El amigo imaginario ya tenía abogado y obra social.',
'Un mapa del barrio conectado con hilo rojo y fotos de deliverys.',
'La réplica de mi propia cabeza guardada dentro del horno.',
'Una libreta con rankings semanales de todas mis personalidades.',
'El sótano estaba decorado exactamente como el jardín de infantes.',
'Una silla vacía a la que todos debían pedirle permiso para sentarse.',
'Cuarenta kilos de arroz formando mi nombre en el piso.',
'La voz del placard solo quería discutir de política.',
'Un grupo de WhatsApp integrado únicamente por mis números alternativos.',
'El funeral simbólico de cada planta que no pude mantener viva.',
'Una alarma que sonaba cada vez que alguien decía la verdad.',
'La pared acolchada era parte de la estética, según el arquitecto.',
'Un álbum familiar donde todas las caras habían sido reemplazadas por la mía.',
'La ouija respondía únicamente con datos de mi tarjeta de crédito.',
'Una valija preparada para huir de una amenaza que inventé yo.',
'El espejo tenía anotaciones sobre cómo mejorar mis discusiones.',
'Una maqueta a escala del departamento con todos durmiendo adentro.',
'La mascota disecada seguía teniendo más seguidores que yo.',
'Un recibo firmado por alguien que oficialmente nunca existió.',
'La contraseña era el nombre completo de mi enemigo imaginario.',
'Una fiesta sorpresa organizada para comprobar quién fingía quererme.',
'El muñeco decía cosas horribles incluso sin pilas.',
'Una urna con las cenizas de todos mis proyectos abandonados.',
'El pasaporte falso decía que mi profesión era “testigo presencial”.',
'Una pala nueva, una coartada vieja y barro en lugares difíciles de explicar.',
'El bolso contenía dinero, pelucas y siete documentos con mi foto.',
'Una transferencia internacional con el concepto “no hacer preguntas”.',
'La patente del auto coincidía con la fecha del supuesto accidente.',
'Un emprendimiento de coartadas personalizadas con entrega en el día.',
'La cámara de seguridad fue reemplazada por un video mío durmiendo.',
'Una bolsa marcada “evidencia” usada para llevar empanadas.',
'El abogado recomendó dejar de contar la anécdota en reuniones.',
'Un pasadizo secreto que desembocaba en la caja del supermercado.',
'La colección completa de llaves de departamentos donde nunca viví.',
'Una factura por servicios de desaparición con descuento por reincidencia.',
'El baúl estaba vacío, salvo por un cartel que decía “llegaron tarde”.',
'Una identidad nueva comprada en doce cuotas sin interés.',
'El dron llevaba tres semanas vigilando al vecino equivocado.',
'Una declaración jurada escrita antes de que ocurriera el delito.',
'La caja fuerte contenía únicamente los planes para abrir otra caja fuerte.',
'Un chaleco reflectante que me permitía entrar a cualquier edificio.',
'La coartada estaba ensayada como un número musical.',
'Un sello oficial fabricado con una papa.',
'El mapa señalaba todas las casas que todavía dejan la llave bajo el felpudo.',
'Una multa enmarcada y firmada por todos los involucrados.',
'El testigo protegido era yo usando anteojos de sol.',
'Un curso online titulado “Lavado de dinero para emprendedores”.',
'La matrícula del médico pertenecía a un veterinario jubilado.',
'Un ticket de estacionamiento que destruía toda mi versión de los hechos.',
'El detector de metales sonó por algo que ningún médico quiso retirar.',
'Una heladera portátil rotulada “órganos”, llena de sánguches de miga.',
'El código QR abría una carpeta llamada “material para el juicio”.',
'La alarma del banco estaba configurada como mi tono de llamada.',
'Una escritura a mi nombre de una propiedad que no existe.',
'La prueba de ADN coincidía con alguien que todavía no había nacido.',
'Un diploma de cirujano descargado como plantilla gratuita.',
'La nota de rescate exigía que me devolvieran el tupper.',
'Un sótano insonorizado alquilado por hora en una aplicación.',
'El uniforme policial tenía cierre de velcro y olor a cotillón.',
'Una caja de guantes, cinta adhesiva y tarjetas de presentación.',
'El plan maestro dependía de que nadie supiera usar Excel.',
'Una orden de restricción utilizada como invitación de cumpleaños.',
'El botín completo estaba declarado como equipaje de mano.',
'La confesión venía con código de descuento y programa de referidos.',
'El colchón tenía más kilómetros que el auto de mi viejo.',
'Un pendrive etiquetado “vacaciones familiares” que definitivamente no tenía vacaciones.',
'La bata de seda era alquilada y debía devolverse antes del amanecer.',
'Un preservativo firmado como si fuera una camiseta de fútbol.',
'La aplicación de citas me reconocía como establecimiento comercial.',
'Un tutorial sensual narrado con la voz de mi contador.',
'Las esposas eran profesionales; el que las usaba, no.',
'Una cama elástica registrada como domicilio fiscal.',
'La contraseña del juguete era el cumpleaños de mi suegra.',
'Una playlist romántica interrumpida por audios del grupo del colegio.',
'El espejo del techo todavía tenía la etiqueta del supermercado.',
'Una caja de bombones rellenos con números de teléfono.',
'El disfraz sexy venía con casco y ART.',
'La reserva del hotel figuraba a nombre de “Congreso de Contadores”.',
'Una foto comprometedora usada como tarjeta navideña.',
'El lubricante estaba guardado junto al chimichurri y nadie quiso preguntar.',
'Una cita de Tinder convertida accidentalmente en asamblea de consorcio.',
'El mayordomo era en realidad mi jefe usando un bigote falso.',
'La noche terminó con una encuesta de desempeño y dos estrellas.',
'Un cajón entero dedicado a cosas que vibran y no tienen garantía.',
'El antifaz decía “propiedad del Ministerio de Economía”.',
'Un mensaje que empezaba con “estoy solo” y terminaba con una denuncia vecinal.',
'La fantasía era menos preocupante antes de incluir una retroexcavadora.',
'Un cupón de dos por uno para una experiencia que debía ser exclusiva.',
'La habitación por hora estaba reservada para una reunión de directorio.',
'Una cabra con mi mismo nombre y acceso a mi cuenta bancaria.',
'El retrato familiar cambiaba de expresión cuando apagábamos la luz.',
'Una caja musical que reproducía mis conversaciones privadas.',
'El espantapájaros tenía dientes humanos, pero una sonrisa encantadora.',
'Un cuaderno con instrucciones dictadas por la tostadora.',
'La planta carnívora figuraba como contacto de emergencia.',
'Un cumpleaños celebrado para una persona que nunca había nacido.',
'El taxidermista aseguraba que esa expresión ya venía de fábrica.',
'Una bañera llena de fideos y una cuchara del tamaño de una pala.',
'El departamento estaba vacío excepto por cuatrocientos relojes sincronizados.',
'Una peluca distinta para cada deuda emocional.',
'La muñeca pestañeaba únicamente cuando alguien mentía.',
'Un certificado que declaraba legalmente muerto a mi sentido común.',
'El fantasma pagaba alquiler y era el más responsable de la casa.',
'Una colección de dientes que, según yo, había ganado jugando al truco.',
'El microondas recibía mensajes de una frecuencia desconocida.',
'Una segunda familia formada íntegramente por actores desempleados.',
'El horóscopo estaba escrito con mi letra desde hacía veinte años.',
'Un frasco etiquetado “lágrimas de Recursos Humanos”.',
'La pared respiraba, pero solamente después de las visitas.',
'Un terapeuta contratado para atender exclusivamente a mis plantas.',
'La réplica del vecino tenía mejores modales que el original.',
'Una invitación a mi propio velorio con barra libre.',
'El gallo del patio conocía demasiados secretos.',
'Una suscripción mensual para recibir mechones de origen desconocido.',
'El cadáver era parte de la decoración hasta que pidió la contraseña del Wi-Fi.',
'Una carta documento enviada desde el futuro.',
'El testamento dejaba todo a quien pudiera sobrevivir una noche en el baño.',
'La urna contenía brillantina, dos tornillos y un pedido de disculpas.',
'Un gemelo secreto que únicamente aparecía para pagar en efectivo.',
'La valija se movía sola y tenía exceso de equipaje.',
'Una secta dedicada a adorar el módem cuando vuelve Internet.',
'El sótano tenía recepción, sala de espera y cinco estrellas en Google.',
'Una voz dentro del freezer que ofrecía asesoramiento financiero.',
'El muñeco inflable estaba anotado como fiscal de mesa.',
'Tres pasaportes, cuatro nombres y una tarjeta de cliente frecuente.',
'El dinero estaba limpio porque lo había lavado en el lavarropas.',
'Una coartada premium sin publicidad y con treinta días de prueba.',
'El plano del banco estaba dibujado detrás de una carta de amor.',
'Un bolso lleno de celulares que recibían llamadas de mi madre.',
'La patente diplomática estaba hecha con cartón y mucha confianza.',
'Un certificado de defunción usado para pedir un descuento de cumpleaños.',
'La cámara oculta transmitía exclusivamente al televisor del vecino.',
'Un uniforme de juez comprado en una tienda de disfraces.',
'La declaración del testigo incluía pausas para mensajes del patrocinador.',
'Una empresa fantasma con empleados del mes.',
'El dinero del rescate fue declarado como propina.',
'Un túnel clandestino con peaje y factura electrónica.',
'La evidencia desapareció durante una mudanza que nadie había organizado.',
'Un manual titulado “Cómo parecer inocente sin exagerar tanto”.',
'La firma falsificada era más linda que la original.',
'Un inhibidor de alarmas que solo apagaba licuadoras.',
'El auto de fuga tenía calcomanía de principiante.',
'Una bolsa con billetes y una nota que decía “para gastos comunes”.',
'El expediente estaba guardado bajo “recetas vegetarianas”.',
'Un detective privado contratado para seguirme a mí mismo.',
'La caja negra contenía los audios del grupo familiar.',
'Un negocio de documentos falsos que aceptaba Mercado Pago.',
'La máscara tenía mi cara, pero veinte años mejor dormida.',
'Un escribano escondido debajo de la mesa validando cada mentira.',
'El operativo secreto tenía merchandising oficial.',
'Una alarma silenciosa que gritaba “¡ALARMA!” cada treinta segundos.',
'El escondite perfecto estaba publicado en Google Maps.',
'Una bóveda bancaria utilizada para guardar tuppers sin tapa.',
'El soborno incluía puntos canjeables y millas aéreas.',
'Una camioneta sin patente con el Instagram del conductor pintado al costado.',
'El contrato ilegal estaba certificado ante escribano.',
'Una fuga internacional organizada por una agencia de turismo estudiantil.',
'La orden judicial venía acompañada por una invitación al after.',
'El sospechoso número uno tenía mi cara y mejores referencias.',
'Un juicio oral transmitido como podcast de comedia.',
'El arma homicida era una impresora que se negaba a funcionar.',
'Una red de contrabando escondida dentro de un club de tejido.',
'La recompensa por mi captura aceptaba cuotas.',
'El interrogatorio terminó cuando empecé a cobrar por hora.'
];
