export const mostLikelyPrompts = [
  '¿Quién es más probable que termine en la cama con dos desconocidos la misma noche?',
  '¿Quién es más probable que mande una foto íntima al grupo equivocado?',
  '¿Quién es más probable que tenga una cuenta secreta para vender contenido picante?',
  '¿Quién es más probable que se enganche con alguien casado y se entere después?',
  '¿Quién es más probable que use esposas y después pierda la llave?',
  '¿Quién es más probable que proponga una noche de a tres?',
  '¿Quién es más probable que tenga un juguete para adultos conectado al Bluetooth?',
  '¿Quién es más probable que se acueste con su ex y lo niegue hasta la muerte?',
  '¿Quién es más probable que tenga una fantasía que necesite casco y seguro médico?',
  '¿Quién es más probable que salga con dos personas sin saber que se conocen?',
  '¿Quién es más probable que convierta una amistad en algo con beneficios?',
  '¿Quién es más probable que haya tenido sexo en un lugar público?',
  '¿Quién es más probable que guarde fotos comprometedoras de todos sus ex?',
  '¿Quién es más probable que mienta sobre la cantidad de personas con las que estuvo?',
  '¿Quién es más probable que tenga una palabra de seguridad completamente ridícula?',
  '¿Quién es más probable que seduzca a alguien solo para conseguir un favor?',
  '¿Quién es más probable que termine desnudo en una casa equivocada?',
  '¿Quién es más probable que mande un audio caliente mientras está en una reunión?',
  '¿Quién es más probable que tenga una aventura durante un viaje de trabajo?',
  '¿Quién es más probable que se enamore de alguien que conoció en una fiesta sexual?',
  '¿Quién es más probable que reserve un hotel por hora y pida factura A?',
  '¿Quién es más probable que tenga un cajón que nadie puede abrir?',
  '¿Quién es más probable que haya grabado un video privado y se arrepienta?',
  '¿Quién es más probable que confunda lubricante con algo de la cocina?',
  '¿Quién es más probable que invite a alguien a dormir con intenciones nada inocentes?',
  '¿Quién es más probable que tenga una cita con alguien solo por una fantasía?',
  '¿Quién es más probable que haya usado un disfraz sexy y terminado en una guardia?',
  '¿Quién es más probable que reciba un paquete discreto durante una cena familiar?',
  '¿Quién es más probable que se levante a alguien en un velorio?',
  '¿Quién es más probable que tenga más juguetes que medias en el cajón?',
  '¿Quién es más probable que organice una fiesta y no recuerde cómo terminó?',
  '¿Quién es más probable que despierte con un tatuaje dedicado a un desconocido?',
  '¿Quién es más probable que hable con un maniquí como si fuera su pareja?',
  '¿Quién es más probable que tenga una habitación secreta en su casa?',
  '¿Quién es más probable que le ponga nombre a cada una de sus personalidades?',
  '¿Quién es más probable que conserve un mechón de pelo de cada ex?',
  '¿Quién es más probable que finja su propia muerte para evitar una deuda?',
  '¿Quién es más probable que arme un altar dedicado a sí mismo?',
  '¿Quién es más probable que tenga cámaras apuntando al pasillo “por seguridad”?',
  '¿Quién es más probable que invite a un fantasma a formar parte de la familia?',
  '¿Quién es más probable que coleccione objetos encontrados en cementerios?',
  '¿Quién es más probable que haga una fiesta temática sobre su propio funeral?',
  '¿Quién es más probable que escuche voces y les pida consejos financieros?',
  '¿Quién es más probable que tenga un mapa del barrio unido con hilos rojos?',
  '¿Quién es más probable que prepare una valija para una invasión alienígena?',
  '¿Quién es más probable que le pague terapia a una planta?',
  '¿Quién es más probable que duerma con los ojos abiertos para asustar a los demás?',
  '¿Quién es más probable que tenga una réplica tamaño real de sí mismo?',
  '¿Quién es más probable que invente un enemigo y después le tenga miedo?',
  '¿Quién es más probable que haya llevado una ouija a una reunión familiar?',
  '¿Quién es más probable que se meta en una secta por el catering?',
  '¿Quién es más probable que cree una religión para no pagar impuestos?',
  '¿Quién es más probable que tenga un sótano insonorizado sin explicación convincente?',
  '¿Quién es más probable que sea expulsado de un cementerio?',
  '¿Quién es más probable que le escriba cartas a alguien que no existe?',
  '¿Quién es más probable que organice su propio secuestro para llamar la atención?',
  '¿Quién es más probable que falsifique un testamento por una colección de tuppers?',
  '¿Quién es más probable que termine interrogado por algo que hizo “por contenido”?',
  '¿Quién es más probable que tenga una coartada preparada para cada día de la semana?',
  '¿Quién es más probable que conozca a un tipo que consigue documentos falsos?',
  '¿Quién es más probable que robe un banco y se olvide de llevar una bolsa?',
  '¿Quién es más probable que intente sobornar a alguien con puntos del supermercado?',
  '¿Quién es más probable que tenga un pasaporte con otro nombre?',
  '¿Quién es más probable que termine preso por hacerse pasar por profesional?',
  '¿Quién es más probable que esconda evidencia dentro de un tupper?',
  '¿Quién es más probable que conduzca el auto de fuga respetando todos los semáforos?',
  '¿Quién es más probable que abra una empresa fantasma y premie al empleado del mes?',
  '¿Quién es más probable que lave dinero literalmente en el lavarropas?',
  '¿Quién es más probable que intente cruzar una frontera dentro de una valija?',
  '¿Quién es más probable que venda una identidad falsa en cuotas?',
  '¿Quién es más probable que tenga una pala nueva y una coartada demasiado vieja?',
  '¿Quién es más probable que falsifique una firma y la haga mejor que la original?',
  '¿Quién es más probable que sea buscado por la policía de un país que nunca visitó?',
  '¿Quién es más probable que declare un soborno como gasto laboral?',
  '¿Quién es más probable que alquile un galpón usando el nombre de su mascota?',
  '¿Quién es más probable que venda algo robado a la misma persona a quien se lo robó?',
  '¿Quién es más probable que se escape de un operativo disfrazado de policía?',
  '¿Quién es más probable que guarde dinero dentro de un colchón ajeno?',
  '¿Quién es más probable que termine en un juicio por una apuesta absurda?',
  '¿Quién es más probable que confiese un delito para impresionar a una cita?',
  '¿Quién es más probable que tenga una orden de restricción enmarcada?',
  '¿Quién es más probable que cree una aplicación para organizar coartadas?',
  '¿Quién es más probable que entre a una casa equivocada y decida quedarse?',
  '¿Quién es más probable que desaparezca una semana y vuelva con acento nuevo?',
  '¿Quién es más probable que venda los secretos del grupo por una cena gratis?',
  '¿Quién es más probable que se case por una herencia y termine enamorado?',
  '¿Quién es más probable que tenga una segunda familia en otra provincia?',
  '¿Quién es más probable que abandone al grupo en medio de un apocalipsis?',
  '¿Quién es más probable que cambie de identidad después de esta partida?',
  '¿Quién es más probable que llegue a su boda acompañado por la policía?',
  '¿Quién es más probable que seduzca al detective que lo está investigando?',
  '¿Quién es más probable que despierte en otro país sin saber cómo llegó?',
  '¿Quién es más probable que venda un órgano y se compre algo completamente inútil?',
  '¿Quién es más probable que convierta un velorio en una oportunidad de negocio?',
  '¿Quién es más probable que tenga las contraseñas de todo el grupo?',
  '¿Quién es más probable que espíe a sus vecinos con un dron?',
  '¿Quién es más probable que sea el villano secreto de esta amistad?',
  '¿Quién es más probable que nos entregue a todos para salvarse?',
  '¿Quién es más probable que termine esta noche en una comisaría?',
  '¿Quién es más probable que sea mencionado en un documental criminal?'
];
