export const trialCases = [
  'Está acusado de usar el grupo familiar para vender contenido para adultos.',
  'Está acusado de organizar una orgía y cobrar entrada sin incluir consumición.',
  'Está acusado de mandar una foto íntima desde el celular de su jefe.',
  'Está acusado de usar las esposas equivocadas durante una noche romántica.',
  'Está acusado de convertir una reunión de consorcio en una despedida de soltero.',
  'Está acusado de tener una doble vida como instructor de seducción.',
  'Está acusado de reservar un hotel por hora con la tarjeta de la empresa.',
  'Está acusado de transmitir accidentalmente una cita privada por Instagram.',
  'Está acusado de vender juguetes para adultos durante un bautismo.',
  'Está acusado de enviar el mismo mensaje picante a siete personas del grupo.',
  'Está acusado de fingir ser masajista para conseguir una cita.',
  'Está acusado de robar lencería y usarla como decoración navideña.',
  'Está acusado de registrar una cama giratoria como maquinaria industrial.',
  'Está acusado de usar la palabra de seguridad para pedir un préstamo.',
  'Está acusado de seducir al encargado para no pagar expensas.',
  'Está acusado de esconder a su amante dentro de un mueble que vendió por Internet.',
  'Está acusado de organizar una cita doble sin avisarle a ninguna de las partes.',
  'Está acusado de usar un juguete conectado al Bluetooth del vecino.',
  'Está acusado de filmar un tutorial sensual en horario laboral.',
  'Está acusado de declarar preservativos como insumos de oficina.',
  'Está acusado de fundar una secta para evitar pagar el asado.',
  'Está acusado de falsificar su muerte para cancelar una primera cita.',
  'Está acusado de alquilar un sótano insonorizado con puntos del supermercado.',
  'Está acusado de guardar una réplica del vecino dentro del placard.',
  'Está acusado de hablar con una paloma y nombrarla heredera universal.',
  'Está acusado de organizar su propio velorio para escuchar qué decían de él.',
  'Está acusado de reemplazar a toda su familia por actores durante Navidad.',
  'Está acusado de construir un altar con objetos robados del consorcio.',
  'Está acusado de secuestrar el maniquí de una vidriera por motivos románticos.',
  'Está acusado de almacenar dientes humanos como si fueran figuritas.',
  'Está acusado de declarar a su amigo imaginario como empleado doméstico.',
  'Está acusado de entrar a un cementerio para grabar contenido patrocinado.',
  'Está acusado de crear un clon para mandarlo a trabajar.',
  'Está acusado de cobrar entrada para mostrar una mancha de humedad milagrosa.',
  'Está acusado de convertir el funeral de una mascota en una fiesta electrónica.',
  'Está acusado de esconder un cadáver de utilería durante seis meses.',
  'Está acusado de enviar cartas documento desde el futuro.',
  'Está acusado de fingir una posesión para evitar una cena familiar.',
  'Está acusado de coleccionar mechones de pelo sin etiquetar su procedencia.',
  'Está acusado de contratar a un exorcista para desalojar a un inquilino.',
  'Está acusado de lavar dinero literalmente dentro de un lavarropas.',
  'Está acusado de abrir una empresa fantasma y despedir a todos sus fantasmas.',
  'Está acusado de vender documentos falsos con programa de referidos.',
  'Está acusado de robar un banco usando una máscara con su propia cara.',
  'Está acusado de sobornar a un policía con millas aéreas vencidas.',
  'Está acusado de esconder evidencia dentro del tupper de su suegra.',
  'Está acusado de cavar un túnel clandestino hacia el supermercado.',
  'Está acusado de contratar a un detective para seguirse a sí mismo.',
  'Está acusado de cruzar una frontera escondido dentro de una piñata.',
  'Está acusado de falsificar un diploma para operar una máquina de peluches.',
  'Está acusado de alquilar un auto de fuga con devolución en otra sucursal.',
  'Está acusado de vender una coartada que ya había usado otra persona.',
  'Está acusado de entrar a casas ajenas vestido como técnico de Internet.',
  'Está acusado de usar una orden judicial como invitación de cumpleaños.',
  'Está acusado de iniciar una red de contrabando dentro de un club de tejido.',
  'Está acusado de esconder dinero en un colchón que luego regaló.',
  'Está acusado de hacerse pasar por juez en una discusión familiar.',
  'Está acusado de conducir una ambulancia para evitar el tránsito.',
  'Está acusado de vender secretos del grupo a cambio de empanadas.',
  'Está acusado de intentar escapar de la policía en un monopatín eléctrico.',
  'Está acusado de usar identidades falsas para obtener descuentos de cumpleaños.',
  'Está acusado de declarar un secuestro como viaje de negocios.',
  'Está acusado de crear pruebas falsas y perderlas antes del juicio.',
  'Está acusado de cobrar rescate por un objeto que nunca tuvo.',
  'Está acusado de falsificar la firma de su mascota en un contrato.',
  'Está acusado de vender un órgano que no era suyo.',
  'Está acusado de guardar las llaves de todas las casas del barrio.',
  'Está acusado de usar un dron para espiar quién le robaba el Wi-Fi.',
  'Está acusado de ofrecer coartadas personalizadas por una aplicación.',
  'Está acusado de provocar un apagón para borrar su historial de búsqueda.',
  'Está acusado de hacerse pasar por sacerdote para escuchar chismes.',
  'Está acusado de llevar un escribano a una cita romántica.',
  'Está acusado de cambiar de identidad para no devolver un tupper.',
  'Está acusado de convertir una comisaría en un espacio de coworking.',
  'Está acusado de esconder el botín en la casa de otro participante.',
  'Está acusado de cometer un delito únicamente para tener una buena anécdota.',
  'Está acusado de fundar una religión cuyo único mandamiento era darle la razón.',
  'Está acusado de organizar su propia captura y vender entradas.',
  'Está acusado de usar pruebas judiciales como decoración del living.',
  'Está acusado de planear una fuga con un tutorial de cinco minutos.'
];
